-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 20:51:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` INT(2) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NULL,
  `celular` INT(11) NULL,
  `cep` INT(8) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `relatorioCompras_idrelatorioCompras` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `relatorioCompras_idrelatorioCompras`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `idusuario_UNIQUE` (`idUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `publico` INT(3) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `adicional` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `embalagem` INT(2) NOT NULL,
  `enderecoEntrega` VARCHAR(45) NOT NULL,
  `cidadeEntrega` VARCHAR(45) NOT NULL,
  `estadoEntrega` VARCHAR(45) NOT NULL,
  `cepEntrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idAdministrador` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoquesProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoquesProduto` (
  `idEstoqueProduto` INT NOT NULL AUTO_INCREMENT,
  `qntEstoque` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `numeracao` INT NOT NULL,
  PRIMARY KEY (`idEstoqueProduto`),
  CONSTRAINT `idproduto`
    FOREIGN KEY ()
    REFERENCES `mydb`.`produtos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_has_pedido` (
  `produto_idProduto` INT NOT NULL,
  `pedido_idPedido` INT NOT NULL,
  `qntProduto` INT NOT NULL,
  PRIMARY KEY (`produto_idProduto`, `pedido_idPedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_idPedido` ASC),
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_idProduto` ASC),
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `mydb`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `mydb`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorioCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorioCompras` (
  `usuarios_idUsuario` INT UNSIGNED NOT NULL,
  `usuarios_relatorioCompras_idrelatorioCompras` INT NOT NULL,
  `pedidos_idPedido` INT NOT NULL,
  PRIMARY KEY (`usuarios_idUsuario`, `usuarios_relatorioCompras_idrelatorioCompras`, `pedidos_idPedido`),
  INDEX `fk_usuarios_has_pedidos_pedidos1_idx` (`pedidos_idPedido` ASC),
  INDEX `fk_usuarios_has_pedidos_usuarios1_idx` (`usuarios_idUsuario` ASC, `usuarios_relatorioCompras_idrelatorioCompras` ASC),
  CONSTRAINT `fk_usuarios_has_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_idUsuario` , `usuarios_relatorioCompras_idrelatorioCompras`)
    REFERENCES `mydb`.`usuarios` (`idUsuario` , `relatorioCompras_idrelatorioCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_idPedido`)
    REFERENCES `mydb`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
