-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 20:27:52 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` INT(2) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NULL,
  `celular` INT(11) NULL,
  `cep` INT(8) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `relatorioCompras_idrelatorioCompras` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `relatorioCompras_idrelatorioCompras`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `publico` INT(3) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `adicional` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `embalagem` INT(2) NOT NULL,
  `enderecoEntrega` VARCHAR(45) NOT NULL,
  `cidadeEntrega` VARCHAR(45) NOT NULL,
  `estadoEntrega` VARCHAR(45) NOT NULL,
  `cepEntrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idadministrador` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoquesProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoquesProduto` (
  `idestoqueProduto` INT NOT NULL AUTO_INCREMENT,
  `qntEstoque` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `numeracao` INT NOT NULL,
  PRIMARY KEY (`idestoqueProduto`),
  CONSTRAINT `idproduto`
    FOREIGN KEY ()
    REFERENCES `mydb`.`produtos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_has_pedido` (
  `produto_idproduto` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `qntProduto` INT NOT NULL,
  PRIMARY KEY (`produto_idproduto`, `pedido_idpedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_idpedido` ASC),
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produtos` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedidos` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorioCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorioCompras` (
  `usuarios_idusuario` INT UNSIGNED NOT NULL,
  `usuarios_relatorioCompras_idrelatorioCompras` INT NOT NULL,
  `pedidos_idpedido` INT NOT NULL,
  PRIMARY KEY (`usuarios_idusuario`, `usuarios_relatorioCompras_idrelatorioCompras`, `pedidos_idpedido`),
  INDEX `fk_usuarios_has_pedidos_pedidos1_idx` (`pedidos_idpedido` ASC),
  INDEX `fk_usuarios_has_pedidos_usuarios1_idx` (`usuarios_idusuario` ASC, `usuarios_relatorioCompras_idrelatorioCompras` ASC),
  CONSTRAINT `fk_usuarios_has_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_idusuario` , `usuarios_relatorioCompras_idrelatorioCompras`)
    REFERENCES `mydb`.`usuarios` (`idusuario` , `relatorioCompras_idrelatorioCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_idpedido`)
    REFERENCES `mydb`.`pedidos` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
